# Generated by Django 2.2.6 on 2019-10-26 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_nummber', models.CharField(max_length=20)),
                ('model_image', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_image', models.ImageField(upload_to='images/')),
                ('chair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Chair')),
            ],
        ),
    ]
